package uk.gov.ons.addressindex.models

import org.apache.spark.sql.types._

object NisraSchema {

  // keep old schema commented out for the mo

  val nisraFileSchema = StructType(Seq(
    StructField("organisationName", StringType),
    StructField("subBuildingName", StringType),
    StructField("buildingName", StringType),
    StructField("buildingNumber", StringType),
    StructField("thoroughfare", StringType),
    StructField("dependentThoroughfare", StringType),
    StructField("locality", StringType),
    StructField("townName", StringType),
    StructField("county", StringType),
    StructField("postcode", StringType),
    StructField("uprn", LongType),
    StructField("localCustodianCode", StringType),
    StructField("blpuState", ByteType),
    StructField("logicalStatus", ByteType),
    StructField("classificationCode", StringType),
    StructField("udprn", IntegerType),
    StructField("postTown", StringType),
    StructField("addressType", StringType),
    StructField("estabType", StringType),
    StructField("oa", StringType),
    StructField("lsoa", StringType),
    StructField("msoa", StringType),
    StructField("lad", StringType),
    StructField("region", StringType),
    StructField("recordIdentifier", ByteType),
    StructField("parentUprn", LongType),
    StructField("usrn", IntegerType),
    StructField("xCoordinate", FloatType),
    StructField("yCoordinate", FloatType),
    StructField("primaryUprn", LongType),
    StructField("secondaryUprn", StringType),
    StructField("thisLayer", IntegerType),
    StructField("layers", IntegerType),
    StructField("nodeType", StringType),
    StructField("creationDate", StringType),
    StructField("commencementDate", StringType),
    StructField("archivedDate", StringType),
    StructField("latitude", FloatType),
    StructField("longitude", FloatType),
    StructField("paoStartNumber", StringType),
    StructField("paoEndNumber", StringType),
    StructField("paoStartSuffix", StringType),
    StructField("paoEndSuffix", StringType),
    StructField("paoText", StringType),
    StructField("saoStartNumber", StringType),
    StructField("saoEndNumber", StringType),
    StructField("saoStartSuffix", StringType),
    StructField("saoEndSuffix", StringType),
    StructField("saoText", StringType),
    StructField("addressLine1", StringType),
    StructField("addressLine2", StringType),
    StructField("addressLine3", StringType),
    StructField("address1YearAgo", StringType)
  ))


//  val nisraFileSchema = StructType(Seq(
//    StructField("organisationName", StringType),
//    StructField("subBuildingName", StringType),
//    StructField("buildingName", StringType),
//    StructField("buildingNumber", StringType),
//    StructField("thoroughfare", StringType),
//    StructField("dependentThoroughfare", StringType),
//    StructField("altThoroughfare", StringType),
//    StructField("locality", StringType),
//    StructField("townland", StringType),
//    StructField("townName", StringType),
//    StructField("county", StringType),
//    StructField("postcode", StringType),
//    StructField("uprn", LongType),
//    StructField("localCustodianCode", StringType),
//    StructField("blpuState", ByteType),
//    StructField("logicalStatus", ByteType),
//    StructField("classificationCode", StringType),
//    StructField("udprn", IntegerType),
//    StructField("postTown", StringType),
//    StructField("addressType", StringType),
//    StructField("estabType", StringType),
//    StructField("oa11", StringType),
//    StructField("lsoa11", StringType),
//    StructField("msoa11", StringType),
//    StructField("lad", StringType),
//    StructField("region", StringType),
//    StructField("recordIdentifier", ByteType),
//    StructField("parentUprn", LongType),
//    StructField("usrn", IntegerType),
//    StructField("xCoordinate", FloatType),
//    StructField("yCoordinate", FloatType),
//    StructField("primaryUprn", LongType),
//    StructField("secondaryUprn", StringType),
//    StructField("thisLayer", IntegerType),
//    StructField("layers", IntegerType),
//    StructField("nodeType", StringType),
//    StructField("creationDate", StringType),
//    StructField("commencementDate", StringType),
//    StructField("archivedDate", StringType),
//    StructField("latitude", FloatType),
//    StructField("longitude", FloatType),
//    StructField("paoStartNumber", StringType),
//    StructField("paoEndNumber", StringType),
//    StructField("paoStartSuffix", StringType),
//    StructField("paoEndSuffix", StringType),
//    StructField("paoText", StringType),
//    StructField("saoStartNumber", StringType),
//    StructField("saoEndNumber", StringType),
//    StructField("saoStartSuffix", StringType),
//    StructField("saoText", StringType),
//    StructField("saoEndSuffix", StringType),
//    StructField("addressLine1", StringType),
//    StructField("addressLine2", StringType),
//    StructField("addressLine3", StringType),
//    StructField("tempCoords", StringType),
//    StructField("WARD2014", StringType),
//    StructField("SOA2001", StringType),
//    StructField("WARD1992", StringType),
//    StructField("LGD1992", StringType),
//    StructField("AA1998", StringType),
//    StructField("AA2008", StringType),
//    StructField("LGD1984", StringType),
//    StructField("WARD1984", StringType),
//    StructField("ED1991_MAP", StringType),
//    StructField("ED1991", StringType),
//    StructField("settlement", StringType),
//    StructField("settlementband", StringType),
//    StructField("NRA_CODE", StringType),
//    StructField("TTWA2007", StringType),
//    StructField("address1YearAgo", StringType)
//  ))
}