package uk.gov.ons.addressindex.models

import org.apache.spark.sql.types._

object NisraSchema {

  val nisraFileSchema = StructType(Seq(
    StructField("organisationName", StringType),
    StructField("subBuildingName", StringType),
    StructField("buildingName", StringType),
    StructField("buildingNumber", StringType),
    StructField("thoroughfare", StringType),
    StructField("dependentThoroughfare", StringType),
    StructField("locality", StringType),
    StructField("townName", StringType),
    StructField("county", StringType),
    StructField("postcode", StringType),
    StructField("uprn", LongType),
    StructField("localCustodianCode", StringType),
    StructField("blpuState", ByteType),
    StructField("logicalStatus", ByteType),
    StructField("classificationCode", StringType),
    StructField("udprn", IntegerType),
    StructField("postTown", StringType),
    StructField("addressType", StringType),
    StructField("estabType", StringType),
    StructField("oa", StringType),
    StructField("lsoa", StringType),
    StructField("msoa", StringType),
    StructField("lad", StringType),
    StructField("region", StringType),
    StructField("recordIdentifier", ByteType),
    StructField("parentUprn", LongType),
    StructField("usrn", IntegerType),
    StructField("xCoordinate", FloatType),
    StructField("yCoordinate", FloatType),
    StructField("primaryUprn", LongType),
    StructField("secondaryUprn", StringType),
    StructField("thisLayer", IntegerType),
    StructField("layers", IntegerType),
    StructField("nodeType", StringType),
    StructField("latitude", FloatType),
    StructField("longitude", FloatType),
    StructField("paoStartNumber", StringType),
    StructField("paoEndNumber", StringType),
    StructField("paoStartSuffix", StringType),
    StructField("paoEndSuffix", StringType),
    StructField("paoText", StringType),
    StructField("saoStartNumber", StringType),
    StructField("saoEndNumber", StringType),
    StructField("saoStartSuffix", StringType),
    StructField("saoEndSuffix", StringType),
    StructField("saoText", StringType),
    StructField("addressLine1", StringType),
    StructField("addressLine2", StringType),
    StructField("addressLine3", StringType),
    StructField("address1YearAgo", StringType)
  ))

}